name: code checks

on:
  - push

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install -g yarn
      - run: npm install -g prettier
      - run: yarn
      - run: yarn lint
      - run: yarn prettier --check "**/*.{ts,tsx}"
      - run: yarn typecheck
